name: Cypress Tests
on:
  schedule:
    - cron: '0 10 * * 3'
    - cron: '0 10 * * 6'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    container: cypress/included:13.17.0
    steps:
      - uses: actions/checkout@v6
      - name: Install dependencies
        run: npm ci
      - name: Run Cypress tests
        run: npx cypress run --browser chrome
