name: TestCafe Tests
on:
  schedule:
    - cron: '0 10 * * 3'
    - cron: '0 10 * * 6'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Run TestCafe tests
        run: npx testcafe "chrome:headless --no-sandbox --disable-dev-shm-usage" tests/TestCafe/ --skip-js-errors
